### ISSUE TITLE
Problem while reading T2Well's OUTPUT file using toughio

### ISSUE THREAD

**Issue by ghost** [keurfonluu/toughio#84] opened 2020-11-22 22:13 UTC
**Description of the desired feature**
I am trying to read and convert T2Well's output file into excel file using toughio. The following code is adopted.
toughio-extract OUTPUT MESH

however, I find the following message error.
--------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.19041.630]
(c) 2020 Microsoft Corporation. All rights reserved.

(base) C:\Users\instadm>cd C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run

(base) C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run>toughio-extract OUTPUT MESH
Traceback (most recent call last):
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\input\tough_helpers.py", line 288, in str2float
return float(s)
ValueError: could not convert string to float: '****'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "c:\users\instadm\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\instadm\anaconda3\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\instadm\anaconda3\Scripts\toughio-extract.exe_main.py", line 7, in
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_cli_extract.py", line 43, in extract
output = read_output(
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\output_helpers.py", line 111, in read
return _reader_map[file_format](
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\output\tough_tough.py", line 19, in read
headers, times, variables = _read_table(f, file_type, label_length)
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\output\tough_tough.py", line 125, in _read_table
tmp += reader(line)
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\output\tough_tough.py", line 96, in
reader = lambda line: [str2float(x) for x in line.split()]
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\output\tough_tough.py", line 96, in
reader = lambda line: [str2float(x) for x in line.split()]
File "c:\users\instadm\anaconda3\lib\site-packages\toughio_io\input\tough_helpers.py", line 292, in str2float
return float("{}e{}".format(significand, exponent))
ValueError: could not convert string to float: 'e****'

(base) C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run>

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by keurfonluu** [comment] 2020-11-22 22:51
Hi,

Please provide a MWE (e.g. a file). I cannot fix an error that I can't reproduce.

**Comment by ghost** [comment] 2020-11-22 22:53
Hi,

I have tried but the output file is big (206 MB). Is there a way to upload it?

**Comment by ghost** [comment] 2020-11-22 23:08
Here is the link for the OUTPUT file.
https://www.dropbox.com/s/cwey4p72w7rky2u/OUTPUT.rar?dl=0

**Comment by ghost** [comment] 2020-11-23 13:40
> Hi,
> 
> Please provide a MWE (e.g. a file). I cannot fix an error that I can't reproduce.

Have you been able to convert the file (in the above link) to excel format using toughio?

**Comment by keurfonluu** [comment] 2020-11-23 23:44
Should be fixed in v1.4.6. Please update `toughio`: `pip install -U toughio --user`.

**Closed as completed by keurfonluu** 2020-11-23 23:44 UTC
